services:
  sqlserver: 
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment: 
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    networks: 
      - microservices-network 
  postgres: 
    image: postgres

networks:
  microservices-network: 
    driver: bridge