services:
  sqlserver: 
    container_name: userdb
    environment: 
      - SA_PASSWORD=Sebastian@User123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
      
  postgres: 
    container_name: recipedb
    image: postgres:16-alpine
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=SebastianPass123
      - POSTGRES_DB=recipe_db
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=scram-sha-256
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      postgres 
      -c password_encryption=scram-sha-256

volumes:
  sqlserver-data: 
    driver: local
  postgres-data: 
    driver: local